# baseurl: homin.dev
relativeURLs: true
canonifyURLs: true
copyright: Homin Lee &lt;ff4500@gmail.com&gt;; All rights reserved
languageCode: ko
title: Homin Lee's blog
theme:
  - PaperMod
  # - github.com/theNewDynamic/gohugo-theme-ananke
taxonomies:
  tag: tags
params:
  author: Homin Lee
  description: Arbitrary hacking logs
  enableRobotsTXT: true
ignoreLogs:
  - warning-goldmark-raw-html