baseurl = "homin.dev"
relativeURLs = true
canonifyURLs = true
copyright = "Homin Lee &lt;ff4500@gmail.com&gt;; All rights reserved"

languageCode = "ko"
title = "Homin Lee's blog"
theme = "ananke"

[taxonomies]
  tag = "tags"

[params]
  author = "Homin Lee"
  description = "Arbitrary hacking logs"
  google_analytics = "G-K14T8YFTE0"
  enableRobotsTXT = true
  disqusShortname = "hominleesblog"

