baseurl = "http://suapapa.github.io/blog/"
languageCode = "en-us"
title = "Homin Lee's blog"
theme = "blueberry-detox"

[taxonomies]
  tag = "tags"

[params]
  description = "Arbitrary hacking logs"
  google_analytics = "UA-65909718-2"
  disqusShortname = "hominleesblog"

