baseurl = "https://homin.dev/blog/"
relativeURLs=true
canonifyURLs=true
languageCode = "en-us"
title = "Homin Lee's blog"
theme = "PaperMod"

[taxonomies]
  tag = "tags"

[params]
  description = "Arbitrary hacking logs"
  google_analytics = "UA-65909718-2"
  disqusShortname = "hominleesblog"

