# baseurl: homin.dev
relativeURLs: true
canonifyURLs: true
copyright: Homin Lee &lt;ff4500@gmail.com&gt;; All rights reserved
languageCode: ko
title: Homin Lee's blog
theme:
  - PaperMod
  # - github.com/theNewDynamic/gohugo-theme-ananke
taxonomies:
  tag: tags
params:
  author: Homin Lee
  description: Arbitrary hacking logs
  enableRobotsTXT: true
  assets:
    favicon: https://homin.dev/asset/favicon/favicon.ico
    favicon16x16: https://homin.dev/asset/favicon/favicon-16x16.png
    favicon32x32: https://homin.dev/asset/favicon/favicon-32x32.png
    apple_touch_icon: https://homin.dev/asset/favicon/apple-touch-icon.png
ignoreLogs:
  - warning-goldmark-raw-html